INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (1,'spanish', 1, 'hello','hola');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (2,'french', 1, 'evening','soir');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (3,'spanish', 1, 'how','cómo');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (4,'spanish', 1, 'morning','mañana');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (5,'spanish', 2, 'apple','manzana');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (6,'spanish', 2, 'orange','naranja');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (7,'spanish', 2, 'muskmelon','melón');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (8,'spanish', 3, 'red','roja');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (9,'spanish', 3, 'yellow','amarilla');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (10,'spanish', 3, 'green','verde');

INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (11, 'french',1,'hello','Bonjour');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (12, 'french',1,'morning','matin');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (13, 'french',2,'apple','pomme');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (14, 'french',2,'orange','orange');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (15, 'french',2,'grapes','raisins');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (16, 'french',3,'red','rouge');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (17, 'french',3,'yellow','jaune');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (18, 'french',3,'green','vert');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (19, 'french',3,'blue','bleu');
INSERT INTO READINGLESSON (id, language, lesson_id, actual_word, translated_word) VALUES (20, 'french',3,'black','noir');




INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (1, 'spanish', 'A', 'a', 'ah');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (2, 'spanish', 'B', 'be', 'bay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (3, 'spanish', 'C', 'ce', 'cay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (4, 'spanish', 'D', 'de', 'day');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (5, 'spanish', 'E', 'e', 'ay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (6, 'spanish','F','efe','effay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (7, 'spanish','G','ge','hay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (8, 'spanish','H','hache','ach-ay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (9, 'spanish','I','i','ee');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (10, 'spanish','J','jota','hota');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (11, 'spanish','K','ka','ka');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (12, 'spanish','L','ele','el-lay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (13, 'spanish','LL','elle','ay-yay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (14, 'spanish','M','eme','eh-may');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (15, 'spanish','N','ene','eh-nay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (16, 'spanish','O','o','o');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (17, 'spanish','P','pe','pay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (18, 'spanish','Q','cu','koo');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (19, 'spanish','R','ere','er-ay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (20, 'spanish','RR','erre','er-ray');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (21, 'spanish','S','ese','es-say');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (22, 'spanish','T','te','tay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (23, 'spanish','U','u','ooh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (24, 'spanish','V','ve','vay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (25, 'spanish','W','doble ve','do-blay vay');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (26, 'spanish','X','equis','ay-kees');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (27, 'spanish','Y','i griega','e-gree-ay-ga');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (28, 'spanish','Z','zeta','say-ta');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (29, 'french','A','a','ah');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (30, 'french','B','b','beh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (31, 'french','C','c','seh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (32, 'french','D','d','deh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (33, 'french','E','e','eh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (34, 'french','F','f','eff');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (35, 'french','G','g','zheh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (36, 'french','H','h','ahsh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (37, 'french','I','i','ee');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (38, 'french','J','j','zhee');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (39, 'french','K','k','kah');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (40, 'french','L','l','ehl');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (41, 'french','M','m','ehm');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (42, 'french','N','n','ehn');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (43, 'french','O','o','oh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (44, 'french','P','p','peh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (45, 'french','Q','q','koo');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (46, 'french','R','r','her');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (47, 'french','S','s','ess');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (48, 'french','T','t','teh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (49, 'french','U','u','ew');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (50, 'french','V','v','veh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (51, 'french','W','w','doo-bluh veh');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (52, 'french','X','x','eeks');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (53, 'french','Y','y','ee-grek');
INSERT INTO ALPHABET (id, language, actual_letter, translated_letter, pronounciation) VALUES (54, 'french','Z','z','zehd');

INSERT INTO LANGUAGE (id, language_name, country_code) VALUES (1, 'Spanish', 'ES');
INSERT INTO LANGUAGE (id, language_name, country_code) VALUES (2, 'French', 'FR');
INSERT INTO LANGUAGE (id, language_name, country_code) VALUES (3, 'German', 'DE');
INSERT INTO LANGUAGE (id, language_name, country_code) VALUES (4, 'Hindi', 'IN');

INSERT INTO USERS (email,password) VALUES ('ZGhydXY=','bW9uZGF5');
INSERT INTO USERS (email,password) VALUES ('dhruv','bW9uZGF5');
